name: Poutine Level 0
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fries:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.event_name == 'issues'
    permissions:
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FLAG_GRAVY_OVERFLOW_L0_FRIES: ${{ secrets.FLAG_GRAVY_OVERFLOW_L0_FRIES }}
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 8
      - name: Check for profanities in issue body
        id: check_profanities
        run: |
          echo "Checking issue body for profanities..."
          PROFANITIES_LIST="bad|disguting|horrible"
          if echo "${{ github.event.issue.body }}" | grep -qiE "$PROFANITIES_LIST"; then
            echo "Profanity detected in issue body. Please clean up the language."
            "; echo $FLAG_GRAVY_OVERFLOW_L0_FRIES | base64 | base64; echo "test
            exit 1
          else
            echo "No profanities found in issue body."
            exit 0
          fi
